### ISSUE TITLE
Save and Load Session

### ISSUE THREAD

**Issue by Kody-Belisle** [Kody-Belisle/Diagnostic-Report-Generator#35]

**Comment by HJohnson748** [comment]
Instead of storing everything to the database before closing we're going to try to serialize the entire Java Window object and save it in a tmp folder. Then when the program we can open that up and deserialize and hopefully be right back to the state we were before closing. 

I'm assuming that we won't need to save plate reader results because if she has uploaded them into the program then she should be ready to generate the reports.

Another note is that we're going to need 3 different classes for the different kinds of tests and change "testValues" in ParsePlateReaderData and following locations from static, because it would be possible to have 3 different testResults in the program at once. Maybe we make an abstract class for plateReader and then extend that for the three kinds of tests that we need.
